services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    networks:
      - browser-monitor

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - browser-monitor

networks:
  browser-monitor:
    driver: bridge
