FROM python:3.10-slim

WORKDIR /app
COPY client.py requirements.client.txt ./

RUN pip install --no-cache-dir -r requirements.client.txt

# Install Playwright browsers
RUN pip install playwright && playwright install chromium

CMD ["python", "client.py"]
